name: Bug Report
description: Report an issue
labels: [checking]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the place to report issues. If you have only questions, please consider to ask them on the [Official Page](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
        Make to sure to provide any information that can help in the resolution of the issue.
        The language used to fill the information is english, but can be in french as long as you're really french native (no google translation).
  
  - type: markdown
    attributes:
      value: "## Versions"
      
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      multiple: true
      options:
        - 1.19.4
        - 1.19.2
    validations:
      required: true
      
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
    validations:
      required: true
      
  - type: input
    id: tombstone-version
    attributes:
      label: Corail Tombstone Version
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "## Issue Description"
             
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen? What are the steps to reproduce it
      placeholder: Try to provide the maximum of details!
    validations:
      required: true

  - type: dropdown
    id: gametype
    attributes:
      label: Gametype
      multiple: true
      options:
        - Singleplayer
        - Dedicated Server
    validations:
      required: true
      
  - type: dropdown
    id: tombstone-only
    attributes:
      label: Happen by testing with only Corail Tombstone (required)
      description: you have been able to make this issue happening with only Corail Tombstone in single player.
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: occurence
    attributes:
      label: Occurence
      description: Is it easy to make this issue occuring ?
      options:
        - "occurs all the time"
        - "occurs rarely"
    validations:
      required: true

  - type: input
    id: relevant-mods
    attributes:
      label: Other relevant mods
      description: |
        if this issue is not happening with only Corail Tombstone, provides the minimal list of mods (max 5) to make the issue happening.
      placeholder: other mods to make the issue happening

  - type: input
    id: log-link
    attributes:
      label: Log Link
      description: |
        paste a link for debug log if you think it might help or if you have a crash.
      placeholder: gist/pastebin link

  - type: checkboxes
    id: valid-forge
    attributes:
      label: Tested without any Forge "alternatives" (Magma, Mohist, and so on)
      description: |
        you didn't use a forge alternative for the provided informations
        if your problem only occurs with such a "hybrid server", it's better to report to them
      options:
        - label: "Yes"
          required: true
 
  - type: checkboxes
    id: valid-launcher
    attributes:
      label: Valid Launcher
      description: you used a standard launcher for the provided informations
      options:
        - label: "Yes"
          required: true